export interface Quote {
  id: number;
  text: string;
  author: string;
  category?: string;
}

export const QUOTES: Quote[] = [
  { id: 1, text: "The only way to do great work is to love what you do.", author: "Steve Jobs", category: "Motivation" },
  { id: 2, text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein", category: "Wisdom" },
  { id: 3, text: "Be yourself; everyone else is already taken.", author: "Oscar Wilde", category: "Wisdom" },
  { id: 4, text: "Two roads diverged in a wood, and I—I took the one less traveled by.", author: "Robert Frost", category: "Literature" },
  { id: 5, text: "The unexamined life is not worth living.", author: "Socrates", category: "Philosophy" },
  { id: 6, text: "Imagination is more important than knowledge.", author: "Albert Einstein", category: "Science" },
  { id: 7, text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius", category: "Wisdom" },
  { id: 8, text: "The journey of a thousand miles begins with a single step.", author: "Lao Tzu", category: "Wisdom" },
  { id: 9, text: "That which does not kill us makes us stronger.", author: "Friedrich Nietzsche", category: "Philosophy" },
  { id: 10, text: "Life is what happens when you're busy making other plans.", author: "John Lennon", category: "Life" },
  { id: 11, text: "The only impossible journey is the one you never begin.", author: "Tony Robbins", category: "Motivation" },
  { id: 12, text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson", category: "Wisdom" },
  { id: 13, text: "Creativity is intelligence having fun.", author: "Albert Einstein", category: "Creativity" },
  { id: 14, text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb", category: "Wisdom" },
  { id: 15, text: "It is never too late to be what you might have been.", author: "George Eliot", category: "Motivation" },
  { id: 16, text: "Everything you can imagine is real.", author: "Pablo Picasso", category: "Art" },
  { id: 17, text: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci", category: "Art" },
  { id: 18, text: "The only thing we have to fear is fear itself.", author: "Franklin D. Roosevelt", category: "Courage" },
  { id: 19, text: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson", category: "Motivation" },
  { id: 20, text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill", category: "Motivation" },
  { id: 21, text: "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate.", author: "Ralph Waldo Emerson", category: "Life" },
  { id: 22, text: "Get your facts first, then you can distort them as you please.", author: "Mark Twain", category: "Humor" },
  { id: 23, text: "I think, therefore I am.", author: "René Descartes", category: "Philosophy" },
  { id: 24, text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela", category: "Motivation" },
  { id: 25, text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney", category: "Motivation" },
  { id: 26, text: "If life were predictable it would cease to be life, and be without flavor.", author: "Eleanor Roosevelt", category: "Life" },
  { id: 27, text: "Life is either a daring adventure or nothing at all.", author: "Helen Keller", category: "Life" },
  { id: 28, text: "Many of life's failures are people who did not realize how close they were to success when they gave up.", author: "Thomas A. Edison", category: "Motivation" },
  { id: 29, text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt", category: "Motivation" },
  { id: 30, text: "Tell me and I forget. Teach me and I remember. Involve me and I learn.", author: "Benjamin Franklin", category: "Education" },
  { id: 31, text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson", category: "Motivation" },
  { id: 32, text: "Nothing in life is to be feared, it is only to be understood.", author: "Marie Curie", category: "Science" },
  { id: 33, text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle", category: "Philosophy" },
  { id: 34, text: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama", category: "Happiness" },
  { id: 35, text: "The best and most beautiful things in the world cannot be seen or even touched — they must be felt with the heart.", author: "Helen Keller", category: "Wisdom" },
  { id: 36, text: "Try not to become a man of success, but rather try to become a man of value.", author: "Albert Einstein", category: "Wisdom" },
  { id: 37, text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle", category: "Wisdom" },
  { id: 38, text: "Whoever is happy will make others happy too.", author: "Anne Frank", category: "Happiness" },
  { id: 39, text: "Do not judge me by my successes, judge me by how many times I fell down and got back up again.", author: "Nelson Mandela", category: "Motivation" },
  { id: 40, text: "The secret of getting ahead is getting started.", author: "Mark Twain", category: "Motivation" },
  { id: 41, text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky", category: "Motivation" },
  { id: 42, text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas A. Edison", category: "Perseverance" },
  { id: 43, text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein", category: "Wisdom" },
  { id: 44, text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt", category: "Motivation" },
  { id: 45, text: "It is better to be hated for what you are than to be loved for what you are not.", author: "André Gide", category: "Wisdom" },
  { id: 46, text: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle", category: "Philosophy" },
  { id: 47, text: "In three words I can sum up everything I've learned about life: it goes on.", author: "Robert Frost", category: "Life" },
  { id: 48, text: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar", category: "Motivation" },
  { id: 49, text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt", category: "Motivation" },
  { id: 50, text: "The mind is everything. What you think you become.", author: "Buddha", category: "Wisdom" },
  { id: 51, text: "The best revenge is massive success.", author: "Frank Sinatra", category: "Motivation" },
  { id: 52, text: "I have a dream that my four little children will one day live in a nation where they will not be judged by the color of their skin but by the content of their character.", author: "Martin Luther King Jr.", category: "Inspiration" },
  { id: 53, text: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", author: "Ralph Waldo Emerson", category: "Wisdom" },
  { id: 54, text: "Twenty years from now you will be more disappointed by the things you didn't do than by the ones you did do.", author: "Mark Twain", category: "Motivation" },
  { id: 55, text: "The only thing necessary for the triumph of evil is for good men to do nothing.", author: "Edmund Burke", category: "Wisdom" },
  { id: 56, text: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington", category: "Compassion" },
  { id: 57, text: "What we achieve inwardly will change outer reality.", author: "Plutarch", category: "Philosophy" },
  { id: 58, text: "The greatest wealth is to live content with little.", author: "Plato", category: "Philosophy" },
  { id: 59, text: "Happiness depends upon ourselves.", author: "Aristotle", category: "Happiness" },
  { id: 60, text: "The only real mistake is the one from which we learn nothing.", author: "John Powell", category: "Education" },
  { id: 61, text: "Positive anything is better than negative nothing.", author: "Elbert Hubbard", category: "Motivation" },
  { id: 62, text: "The greatest weapon against stress is our ability to choose one thought over another.", author: "William James", category: "Wisdom" },
  { id: 63, text: "In the end, we will remember not the words of our enemies, but the silence of our friends.", author: "Martin Luther King Jr.", category: "Inspiration" },
  { id: 64, text: "To handle yourself, use your head; to handle others, use your heart.", author: "Eleanor Roosevelt", category: "Wisdom" },
  { id: 65, text: "Courage is not the absence of fear, but rather the assessment that something is more important than fear.", author: "Franklin D. Roosevelt", category: "Courage" },
  { id: 66, text: "The only way to have a friend is to be one.", author: "Ralph Waldo Emerson", category: "Friendship" },
  { id: 67, text: "If you look at what you have in life, you'll always have more.", author: "Oprah Winfrey", category: "Gratitude" },
  { id: 68, text: "Experience is the teacher of all things.", author: "Julius Caesar", category: "Wisdom" },
  { id: 69, text: "The greater the difficulty, the more the glory in surmounting it.", author: "Epicurus", category: "Motivation" },
  { id: 70, text: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde", category: "Life" },
  { id: 71, text: "The secret of happiness is freedom, the secret of freedom is courage.", author: "Carrie Jones", category: "Happiness" },
  { id: 72, text: "Fortune favors the bold.", author: "Virgil", category: "Courage" },
  { id: 73, text: "The only person you should try to be better than is the person you were yesterday.", author: "Anonymous", category: "Motivation" },
  { id: 74, text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe", category: "Motivation" },
  { id: 75, text: "The most important thing is to enjoy your life — to be happy — it's all that matters.", author: "Audrey Hepburn", category: "Life" },
  { id: 76, text: "Life is really simple, but we insist on making it complicated.", author: "Confucius", category: "Wisdom" },
  { id: 77, text: "Keep your face always toward the sunshine — and shadows will fall behind you.", author: "Walt Whitman", category: "Motivation" },
  { id: 78, text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela", category: "Perseverance" },
  { id: 79, text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt", category: "Motivation" },
  { id: 80, text: "Don't count the days, make the days count.", author: "Muhammad Ali", category: "Motivation" },
  { id: 81, text: "He who has a why to live can bear almost any how.", author: "Friedrich Nietzsche", category: "Philosophy" },
  { id: 82, text: "To succeed in life, you need two things: ignorance and confidence.", author: "Mark Twain", category: "Humor" },
  { id: 83, text: "The best way to predict the future is to create it.", author: "Peter Drucker", category: "Motivation" },
  { id: 84, text: "I have no special talents. I am only passionately curious.", author: "Albert Einstein", category: "Science" },
  { id: 85, text: "Well done is better than well said.", author: "Benjamin Franklin", category: "Wisdom" },
  { id: 86, text: "The only source of knowledge is experience.", author: "Albert Einstein", category: "Education" },
  { id: 87, text: "You may say I'm a dreamer, but I'm not the only one.", author: "John Lennon", category: "Inspiration" },
  { id: 88, text: "Wise men speak because they have something to say; fools because they have to say something.", author: "Plato", category: "Philosophy" },
  { id: 89, text: "The only thing we know about the future is that it will be different.", author: "Peter Drucker", category: "Wisdom" },
  { id: 90, text: "Change your thoughts and you change your world.", author: "Norman Vincent Peale", category: "Motivation" },
  { id: 91, text: "It's not the years in your life that count. It's the life in your years.", author: "Abraham Lincoln", category: "Life" },
  { id: 92, text: "The important thing is not to stop questioning.", author: "Albert Einstein", category: "Science" },
  { id: 93, text: "If you want something done, ask a busy person to do it.", author: "Laura Ingalls Wilder", category: "Productivity" },
  { id: 94, text: "Things work out best for those who make the best of how things work out.", author: "John Wooden", category: "Wisdom" },
  { id: 95, text: "A man is but what he knows.", author: "Francis Bacon", category: "Education" },
  { id: 96, text: "The art of being wise is the art of knowing what to overlook.", author: "William James", category: "Wisdom" },
  { id: 97, text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu", category: "Wisdom" },
  { id: 98, text: "The smallest act of kindness is worth more than the grandest intention.", author: "Oscar Wilde", category: "Kindness" },
  { id: 99, text: "If you tell the truth, you don't have to remember anything.", author: "Mark Twain", category: "Humor" },
  { id: 100, text: "Time you enjoy wasting was not wasted.", author: "John Lennon", category: "Life" },
  { id: 101, text: "Life isn't about finding yourself. It's about creating yourself.", author: "George Bernard Shaw", category: "Life" },
  { id: 102, text: "The shoe that fits one person pinches another; there is no recipe for living that suits all cases.", author: "Carl Jung", category: "Wisdom" },
  { id: 103, text: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin", category: "Education" },
  { id: 104, text: "The best preparation for tomorrow is doing your best today.", author: "H. Jackson Brown Jr.", category: "Motivation" },
  { id: 105, text: "It's not whether you get knocked down, it's whether you get up.", author: "Vince Lombardi", category: "Perseverance" },
  { id: 106, text: "Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away.", author: "Antoine de Saint-Exupéry", category: "Wisdom" },
  { id: 107, text: "We cannot solve our problems with the same thinking we used when we created them.", author: "Albert Einstein", category: "Science" },
  { id: 108, text: "The only way to discover the limits of the possible is to go beyond them into the impossible.", author: "Arthur C. Clarke", category: "Science" },
  { id: 109, text: "Reading is to the mind what exercise is to the body.", author: "Joseph Addison", category: "Education" },
  { id: 110, text: "It is better to be feared than loved, if you cannot be both.", author: "Niccolò Machiavelli", category: "Philosophy" },
  { id: 111, text: "Not all those who wander are lost.", author: "J.R.R. Tolkien", category: "Literature" },
  { id: 112, text: "All we have to decide is what to do with the time that is given us.", author: "J.R.R. Tolkien", category: "Literature" },
  { id: 113, text: "So it goes.", author: "Kurt Vonnegut", category: "Literature" },
  { id: 114, text: "It was love at first sight, at last sight, at ever and ever sight.", author: "Vladimir Nabokov", category: "Literature" },
  { id: 115, text: "A day without sunshine is like, you know, night.", author: "Steve Martin", category: "Humor" },
  { id: 116, text: "The early bird gets the worm, but the second mouse gets the cheese.", author: "Steven Wright", category: "Humor" },
  { id: 117, text: "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.", author: "Maya Angelou", category: "Wisdom" },
  { id: 118, text: "The most common way people give up their power is by thinking they don't have any.", author: "Alice Walker", category: "Empowerment" },
  { id: 119, text: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi", category: "Inspiration" },
  { id: 120, text: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett", category: "Motivation" },
  { id: 121, text: "Failure is the condiment that gives success its flavor.", author: "Truman Capote", category: "Perseverance" },
  { id: 122, text: "Happiness is not by chance, but by choice.", author: "Jim Rohn", category: "Happiness" },
  { id: 123, text: "The world is full of magical things patiently waiting for our wits to grow sharper.", author: "Bertrand Russell", category: "Wisdom" },
  { id: 124, text: "I am not a product of my circumstances. I am a product of my decisions.", author: "Stephen R. Covey", category: "Motivation" },
  { id: 125, text: "The only person who never makes mistakes is the person who never does anything.", author: "Theodore Roosevelt", category: "Wisdom" },
  { id: 126, text: "It is better to travel well than to arrive.", author: "Buddha", category: "Life" },
  { id: 127, text: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi", category: "Inspiration" },
  { id: 128, text: "A room without books is like a body without a soul.", author: "Marcus Tullius Cicero", category: "Literature" },
  { id: 129, text: "I have measured out my life with coffee spoons.", author: "T.S. Eliot", category: "Literature" },
  { id: 130, text: "The only thing that interferes with my learning is my education.", author: "Albert Einstein", category: "Education" },
  { id: 131, text: "Life is like a box of chocolates. You never know what you're gonna get.", author: "Forrest Gump", category: "Life" },
  { id: 132, text: "In the end, it's not the years in your life that count. It's the life in your years.", author: "Abraham Lincoln", category: "Life" },
  { id: 133, text: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford", category: "Motivation" },
  { id: 134, text: "The secret of getting ahead is getting started.", author: "Mark Twain", category: "Motivation" },
  { id: 135, text: "The only way to do great work is to love what you do.", author: "Steve Jobs", category: "Motivation" },
  { id: 136, text: "Stay hungry, stay foolish.", author: "Steve Jobs", category: "Motivation" },
  { id: 137, text: "Life is what we make it, always has been, always will be.", author: "Grandma Moses", category: "Life" },
  { id: 138, text: "The greatest pleasure in life is doing what people say you cannot do.", author: "Walter Bagehot", category: "Motivation" },
  { id: 139, text: "What we dwell on is what we become.", author: "Oprah Winfrey", category: "Motivation" },
  { id: 140, text: "If you want to make the world a better place, take a look at yourself and make a change.", author: "Michael Jackson", category: "Inspiration" },
  { id: 141, text: "The only impossible journey is the one you never begin.", author: "Tony Robbins", category: "Motivation" },
  { id: 142, text: "Happiness is an inside job.", author: "William Arthur Ward", category: "Happiness" },
  { id: 143, text: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs", category: "Life" },
  { id: 144, text: "We are what we believe we are.", author: "C.S. Lewis", category: "Wisdom" },
  { id: 145, text: "Courage is knowing what not to fear.", author: "Plato", category: "Courage" },
  { id: 146, text: "The more you know, the more you realize you don't know.", author: "Aristotle", category: "Education" },
  { id: 147, text: "To know what you know and what you do not know, that is true knowledge.", author: "Confucius", category: "Wisdom" },
  { id: 148, text: "The greatest teacher, failure is.", author: "Yoda", category: "Perseverance" },
  { id: 149, text: "Do. Or do not. There is no try.", author: "Yoda", category: "Motivation" },
  { id: 150, text: "In a gentle way, you can shake the world.", author: "Mahatma Gandhi", category: "Inspiration" },
  { id: 151, text: "There is no passion to be found playing small — in settling for a life that is less than the one you are capable of living.", author: "Nelson Mandela", category: "Motivation" },
  { id: 152, text: "Everything has beauty, but not everyone sees it.", author: "Confucius", category: "Wisdom" },
  { id: 153, text: "When you reach the end of your rope, tie a knot in it and hang on.", author: "Franklin D. Roosevelt", category: "Perseverance" },
  { id: 154, text: "The best way to find yourself is to lose yourself in the service of others.", author: "Mahatma Gandhi", category: "Compassion" },
  { id: 155, text: "If you can't explain it simply, you don't understand it well enough.", author: "Albert Einstein", category: "Science" },
  { id: 156, text: "We make a living by what we get, but we make a life by what we give.", author: "Winston Churchill", category: "Life" },
  { id: 157, text: "Success is stumbling from failure to failure with no loss of enthusiasm.", author: "Winston Churchill", category: "Perseverance" },
  { id: 158, text: "Never, never, never give up.", author: "Winston Churchill", category: "Perseverance" },
  { id: 159, text: "The truth is rarely pure and never simple.", author: "Oscar Wilde", category: "Wisdom" },
  { id: 160, text: "A life is not important except in the impact it has on other lives.", author: "Jackie Robinson", category: "Life" },
  { id: 161, text: "First, have a definite, clear practical ideal; a goal, an objective. Second, have the necessary means to achieve your ends; wisdom, money, materials, and methods. Third, adjust all your means to that end.", author: "Aristotle", category: "Philosophy" },
  { id: 162, text: "If we did all the things we are capable of, we would literally astound ourselves.", author: "Thomas A. Edison", category: "Motivation" },
  { id: 163, text: "Great minds discuss ideas; average minds discuss events; small minds discuss people.", author: "Eleanor Roosevelt", category: "Wisdom" },
  { id: 164, text: "We may encounter many defeats but we must not be defeated.", author: "Maya Angelou", category: "Perseverance" },
  { id: 165, text: "If you're going through hell, keep going.", author: "Winston Churchill", category: "Perseverance" },
  { id: 166, text: "No act of kindness, no matter how small, is ever wasted.", author: "Aesop", category: "Kindness" },
  { id: 167, text: "With great power comes great responsibility.", author: "Voltaire", category: "Wisdom" },
  { id: 168, text: "Do not take life too seriously. You will never get out of it alive.", author: "Elbert Hubbard", category: "Humor" },
  { id: 169, text: "The most wasted of all days is one without laughter.", author: "E.E. Cummings", category: "Happiness" },
  { id: 170, text: "Peace begins with a smile.", author: "Mother Teresa", category: "Peace" },
  { id: 171, text: "Not everything that counts can be counted, and not everything that can be counted counts.", author: "William Bruce Cameron", category: "Wisdom" },
  { id: 172, text: "What is essential is invisible to the eye.", author: "Antoine de Saint-Exupéry", category: "Literature" },
  { id: 173, text: "All that glitters is not gold.", author: "William Shakespeare", category: "Literature" },
  { id: 174, text: "To thine own self be true.", author: "William Shakespeare", category: "Literature" },
  { id: 175, text: "Love all, trust a few, do wrong to none.", author: "William Shakespeare", category: "Literature" },
  { id: 176, text: "The course of true love never did run smooth.", author: "William Shakespeare", category: "Literature" },
  { id: 177, text: "What's in a name? That which we call a rose by any other name would smell as sweet.", author: "William Shakespeare", category: "Literature" },
  { id: 178, text: "There is nothing either good or bad, but thinking makes it so.", author: "William Shakespeare", category: "Literature" },
  { id: 179, text: "The fault, dear Brutus, is not in our stars, but in ourselves.", author: "William Shakespeare", category: "Literature" },
  { id: 180, text: "If music be the food of love, play on.", author: "William Shakespeare", category: "Literature" },
  { id: 181, text: "Better three hours too soon than a minute too late.", author: "William Shakespeare", category: "Literature" },
  { id: 182, text: "I can no other answer make but thanks, and thanks, and ever thanks.", author: "William Shakespeare", category: "Literature" },
  { id: 183, text: "A rose by any other name would smell as sweet.", author: "William Shakespeare", category: "Literature" },
  { id: 184, text: "We know what we are, but know not what we may be.", author: "William Shakespeare", category: "Literature" },
  { id: 185, text: "Conscience doth make cowards of us all.", author: "William Shakespeare", category: "Literature" },
  { id: 186, text: "Life is not a problem to be solved, but a reality to be experienced.", author: "Søren Kierkegaard", category: "Philosophy" },
  { id: 187, text: "The mystery of human existence lies not in just staying alive, but in finding something to live for.", author: "Fyodor Dostoevsky", category: "Literature" },
  { id: 188, text: "Beauty is in the eye of the beholder.", author: "Margaret Wolfe Hungerford", category: "Wisdom" },
  { id: 189, text: "Think left and think right and think low and think high. Oh, the thinks you can think up if only you try!", author: "Dr. Seuss", category: "Creativity" },
  { id: 190, text: "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.", author: "Dr. Seuss", category: "Motivation" },
  { id: 191, text: "Today you are you! That is truer than true! There is no one alive who is you-er than you!", author: "Dr. Seuss", category: "Motivation" },
  { id: 192, text: "The more that you read, the more things you will know. The more that you learn, the more places you'll go.", author: "Dr. Seuss", category: "Education" },
  { id: 193, text: "So many books, so little time.", author: "Frank Zappa", category: "Literature" },
  { id: 194, text: "A dream without ambition is like a car without gas.", author: "Anonymous", category: "Motivation" },
  { id: 195, text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson", category: "Motivation" },
  { id: 196, text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair", category: "Courage" },
  { id: 197, text: "The greatest risk is not taking one.", author: "Anonymous", category: "Courage" },
  { id: 198, text: "Small daily improvements over time lead to stunning results.", author: "Robin Sharma", category: "Motivation" },
  { id: 199, text: "The secret of your future is hidden in your daily routine.", author: "Mike Murdock", category: "Productivity" },
  { id: 200, text: "Dream big and dare to fail.", author: "Norman Vaughan", category: "Motivation" },
  { id: 201, text: "Champions keep playing until they get it right.", author: "Billie Jean King", category: "Perseverance" },
  { id: 202, text: "Pressure is a privilege — it only comes to those who earn it.", author: "Billie Jean King", category: "Motivation" },
  { id: 203, text: "Tough times never last, but tough people do.", author: "Robert H. Schuller", category: "Perseverance" },
  { id: 204, text: "Fall seven times, stand up eight.", author: "Japanese Proverb", category: "Perseverance" },
  { id: 205, text: "Kind words can be short and easy to speak, but their echoes are truly endless.", author: "Mother Teresa", category: "Kindness" },
  { id: 206, text: "The sun himself is weak when he first rises, and gathers strength and courage as the day gets on.", author: "Charles Dickens", category: "Motivation" },
  { id: 207, text: "Have a heart that never hardens, and a temper that never tires, and a touch that never hurts.", author: "Charles Dickens", category: "Wisdom" },
  { id: 208, text: "It was the best of times, it was the worst of times.", author: "Charles Dickens", category: "Literature" },
  { id: 209, text: "Please, sir, may I have some more?", author: "Charles Dickens", category: "Literature" },
  { id: 210, text: "A loving heart is the truest wisdom.", author: "Charles Dickens", category: "Wisdom" },
  { id: 211, text: "Ask not what your country can do for you — ask what you can do for your country.", author: "John F. Kennedy", category: "Inspiration" },
  { id: 212, text: "Those who dare to fail miserably can achieve greatly.", author: "John F. Kennedy", category: "Courage" },
  { id: 213, text: "Efforts and courage are not enough without purpose and direction.", author: "John F. Kennedy", category: "Motivation" },
  { id: 214, text: "Every accomplishment starts with the decision to try.", author: "Anonymous", category: "Motivation" },
  { id: 215, text: "What is not started today is never finished tomorrow.", author: "Johann Wolfgang von Goethe", category: "Motivation" },
  { id: 216, text: "Knowing is not enough; we must apply. Willing is not enough; we must do.", author: "Johann Wolfgang von Goethe", category: "Motivation" },
  { id: 217, text: "Everything is hard before it is easy.", author: "Johann Wolfgang von Goethe", category: "Wisdom" },
  { id: 218, text: "The way you see people is the way you treat them, and the way you treat them is what they become.", author: "Johann Wolfgang von Goethe", category: "Wisdom" },
  { id: 219, text: "None are more hopelessly enslaved than those who falsely believe they are free.", author: "Johann Wolfgang von Goethe", category: "Philosophy" },
  { id: 220, text: "No one has ever become poor by giving.", author: "Anne Frank", category: "Kindness" },
  { id: 221, text: "How wonderful it is that nobody need wait a single moment before starting to improve the world.", author: "Anne Frank", category: "Inspiration" },
  { id: 222, text: "Think of all the beauty still left around you and be happy.", author: "Anne Frank", category: "Happiness" },
  { id: 223, text: "Despite everything, I believe that people are really good at heart.", author: "Anne Frank", category: "Inspiration" },
  { id: 224, text: "The best and most beautiful things in the world cannot be seen or even touched — they must be felt with the heart.", author: "Helen Keller", category: "Wisdom" },
  { id: 225, text: "Alone we can do so little; together we can do so much.", author: "Helen Keller", category: "Teamwork" },
  { id: 226, text: "Walking with a friend in the dark is better than walking alone in the light.", author: "Helen Keller", category: "Friendship" },
  { id: 227, text: "Life is either a daring adventure or nothing at all.", author: "Helen Keller", category: "Life" },
  { id: 228, text: "Science is the poetry of reality.", author: "Richard Dawkins", category: "Science" },
  { id: 229, text: "The universe is under no obligation to make sense to you.", author: "Neil deGrasse Tyson", category: "Science" },
  { id: 230, text: "Somewhere, something incredible is waiting to be known.", author: "Carl Sagan", category: "Science" },
  { id: 231, text: "We are made of starstuff.", author: "Carl Sagan", category: "Science" },
  { id: 232, text: "The nitrogen in our DNA, the calcium in our teeth, the iron in our blood — all were made in the interiors of collapsing stars.", author: "Carl Sagan", category: "Science" },
  { id: 233, text: "For small creatures such as we, the vastness is bearable only through love.", author: "Carl Sagan", category: "Science" },
  { id: 234, text: "Look again at that dot. That's here. That's home. That's us.", author: "Carl Sagan", category: "Science" },
  { id: 235, text: "Injustice anywhere is a threat to justice everywhere.", author: "Martin Luther King Jr.", category: "Justice" },
  { id: 236, text: "Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.", author: "Martin Luther King Jr.", category: "Inspiration" },
  { id: 237, text: "Freedom is never voluntarily given by the oppressor; it must be demanded by the oppressed.", author: "Martin Luther King Jr.", category: "Justice" },
  { id: 238, text: "Life's most persistent and urgent question is, 'What are you doing for others?'", author: "Martin Luther King Jr.", category: "Compassion" },
  { id: 239, text: "Our lives begin to end the day we become silent about things that matter.", author: "Martin Luther King Jr.", category: "Inspiration" },
  { id: 240, text: "Intelligence plus character — that is the goal of true education.", author: "Martin Luther King Jr.", category: "Education" },
  { id: 241, text: "The function of education is to teach one to think intensively and to think critically.", author: "Martin Luther King Jr.", category: "Education" },
  { id: 242, text: "Impossible is just a big word thrown around by small men who find it easier to live in the world they've been given than to explore the power they have to change it.", author: "Muhammad Ali", category: "Motivation" },
  { id: 243, text: "Float like a butterfly, sting like a bee.", author: "Muhammad Ali", category: "Motivation" },
  { id: 244, text: "The man who views the world at 50 the same as he did at 20 has wasted 30 years of his life.", author: "Muhammad Ali", category: "Wisdom" },
  { id: 245, text: "It isn't the mountains ahead to climb that wear you out; it's the pebble in your shoe.", author: "Muhammad Ali", category: "Wisdom" },
  { id: 246, text: "If my mind can conceive it, and my heart can believe it, then I can achieve it.", author: "Muhammad Ali", category: "Motivation" },
  { id: 247, text: "The past is a foreign country; they do things differently there.", author: "L.P. Hartley", category: "Literature" },
  { id: 248, text: "All happy families are alike; each unhappy family is unhappy in its own way.", author: "Leo Tolstoy", category: "Literature" },
  { id: 249, text: "Everyone thinks of changing the world, but no one thinks of changing himself.", author: "Leo Tolstoy", category: "Wisdom" },
  { id: 250, text: "We can know only that we know nothing. And that is the highest degree of human wisdom.", author: "Leo Tolstoy", category: "Philosophy" },
  { id: 251, text: "It is amazing how complete is the delusion that beauty is goodness.", author: "Leo Tolstoy", category: "Literature" },
  { id: 252, text: "All that we see or seem is but a dream within a dream.", author: "Edgar Allan Poe", category: "Literature" },
  { id: 253, text: "I have great faith in fools — self-confidence my friends call it.", author: "Edgar Allan Poe", category: "Literature" },
  { id: 254, text: "Deep into that darkness peering, long I stood there, wondering, fearing, doubting, dreaming dreams no mortal ever dared to dream before.", author: "Edgar Allan Poe", category: "Literature" },
  { id: 255, text: "Words have no power to impress the mind without the exquisite horror of their reality.", author: "Edgar Allan Poe", category: "Literature" },
  { id: 256, text: "Men have called me mad, but the question is not yet settled, whether madness is or is not the loftiest intelligence.", author: "Edgar Allan Poe", category: "Literature" },
  { id: 257, text: "A dreamer is one who can only find his way by moonlight, and his punishment is that he sees the dawn before the rest of the world.", author: "Oscar Wilde", category: "Literature" },
  { id: 258, text: "Experience is simply the name we give our mistakes.", author: "Oscar Wilde", category: "Wisdom" },
  { id: 259, text: "Some cause happiness wherever they go; others whenever they go.", author: "Oscar Wilde", category: "Humor" },
  { id: 260, text: "Life is too important to be taken seriously.", author: "Oscar Wilde", category: "Humor" },
  { id: 261, text: "Sarcasm is the lowest form of wit but the highest form of intelligence.", author: "Oscar Wilde", category: "Humor" },
  { id: 262, text: "The world is a stage, but the play is badly cast.", author: "Oscar Wilde", category: "Humor" },
  { id: 263, text: "I am so clever that sometimes I don't understand a single word of what I am saying.", author: "Oscar Wilde", category: "Humor" },
  { id: 264, text: "Looking good and feeling good go hand in hand. If you have a healthy lifestyle, your diet and your body will reflect that.", author: "Misty Copeland", category: "Health" },
  { id: 265, text: "The best thing you can do is master the chaos in you. You are not thrown into the fire, you are the fire.", author: "Misty Copeland", category: "Motivation" },
  { id: 266, text: "Success is not measured by money or power or social rank. Success is measured by your discipline and inner peace.", author: "Mike Ditka", category: "Wisdom" },
  { id: 267, text: "If you want to change your life, change your mind.", author: "Anonymous", category: "Motivation" },
  { id: 268, text: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn", category: "Motivation" },
  { id: 269, text: "Formal education will make you a living; self-education will make you a fortune.", author: "Jim Rohn", category: "Education" },
  { id: 270, text: "Either you run the day, or the day runs you.", author: "Jim Rohn", category: "Productivity" },
  { id: 271, text: "Don't wish it were easier. Wish you were better.", author: "Jim Rohn", category: "Motivation" },
  { id: 272, text: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Rohn", category: "Motivation" },
  { id: 273, text: "Success is nothing more than a few simple disciplines, practiced every day.", author: "Jim Rohn", category: "Motivation" },
  { id: 274, text: "You cannot change your destination overnight, but you can change your direction overnight.", author: "Jim Rohn", category: "Motivation" },
  { id: 275, text: "Happiness is not something you postpone for the future; it is something you design for the present.", author: "Jim Rohn", category: "Happiness" },
  { id: 276, text: "Let others lead small lives, but not you. Let others argue over small things, but not you.", author: "Jim Rohn", category: "Motivation" },
  { id: 277, text: "If you don't design your own life plan, chances are you'll fall into someone else's plan.", author: "Jim Rohn", category: "Life" },
  { id: 278, text: "To live a creative life, we must lose our fear of being wrong.", author: "Joseph Chilton Pearce", category: "Creativity" },
  { id: 279, text: "The greatest danger for most of us is not that our aim is too high and we miss it, but that it is too low and we reach it.", author: "Michelangelo", category: "Motivation" },
  { id: 280, text: "I am always doing that which I cannot do, in order that I may learn how to do it.", author: "Pablo Picasso", category: "Creativity" },
  { id: 281, text: "Every child is an artist. The problem is how to remain an artist once we grow up.", author: "Pablo Picasso", category: "Art" },
  { id: 282, text: "Art washes away from the soul the dust of everyday life.", author: "Pablo Picasso", category: "Art" },
  { id: 283, text: "There is no abstract art. You must always start with something. Afterward you can remove all traces of reality.", author: "Pablo Picasso", category: "Art" },
  { id: 284, text: "It took me four years to paint like Raphael, but a lifetime to paint like a child.", author: "Pablo Picasso", category: "Art" },
  { id: 285, text: "The purpose of art is washing the dust of daily life off our souls.", author: "Pablo Picasso", category: "Art" },
  { id: 286, text: "Art is the lie that enables us to realize the truth.", author: "Pablo Picasso", category: "Art" },
  { id: 287, text: "I shut my eyes in order to see.", author: "Paul Gauguin", category: "Art" },
  { id: 288, text: "Great things are done by a series of small things brought together.", author: "Vincent van Gogh", category: "Art" },
  { id: 289, text: "I dream my painting and I paint my dream.", author: "Vincent van Gogh", category: "Art" },
  { id: 290, text: "If you hear a voice within you say 'you cannot paint,' then by all means paint, and that voice will be silenced.", author: "Vincent van Gogh", category: "Art" },
  { id: 291, text: "The only time I feel alive is when I'm painting.", author: "Vincent van Gogh", category: "Art" },
  { id: 292, text: "I put my heart and my soul into my work, and have lost my mind in the process.", author: "Vincent van Gogh", category: "Art" },
  { id: 293, text: "Music can change the world because it can change people.", author: "Bono", category: "Music" },
  { id: 294, text: "Without music, life would be a mistake.", author: "Friedrich Nietzsche", category: "Music" },
  { id: 295, text: "Music is the universal language of mankind.", author: "Henry Wadsworth Longfellow", category: "Music" },
  { id: 296, text: "Where words fail, music speaks.", author: "Hans Christian Andersen", category: "Music" },
  { id: 297, text: "Music is the strongest form of magic.", author: "Marilyn Manson", category: "Music" },
  { id: 298, text: "One good thing about music, when it hits you, you feel no pain.", author: "Bob Marley", category: "Music" },
  { id: 299, text: "Music expresses that which cannot be said and on which it is impossible to be silent.", author: "Victor Hugo", category: "Music" },
  { id: 300, text: "Science and music are the two most powerful ways of accessing the sublime.", author: "Brian Eno", category: "Music" },
  { id: 301, text: "The only truth is music.", author: "Jack Kerouac", category: "Music" },
  { id: 302, text: "Everything in the universe has rhythm. Everything dances.", author: "Maya Angelou", category: "Music" },
  { id: 303, text: "Be silent or let thy words be worth more than silence.", author: "Pythagoras", category: "Wisdom" },
  { id: 304, text: "The wise speak only of what they know.", author: "J.R.R. Tolkien", category: "Literature" },
  { id: 305, text: "Even the smallest person can change the course of the future.", author: "J.R.R. Tolkien", category: "Literature" },
  { id: 306, text: "Faithless is he that says farewell when the road darkens.", author: "J.R.R. Tolkien", category: "Literature" },
  { id: 307, text: "A safe fairyland is untrue to all worlds.", author: "J.R.R. Tolkien", category: "Literature" },
  { id: 308, text: "Courage is found in unlikely places.", author: "J.R.R. Tolkien", category: "Courage" },
  { id: 309, text: "Where there's life there's hope.", author: "J.R.R. Tolkien", category: "Literature" },
  { id: 310, text: "If more of us valued food and cheer and song above hoarded gold, it would be a merrier world.", author: "J.R.R. Tolkien", category: "Literature" },
  { id: 311, text: "The world is indeed full of peril, and in it there are many dark places; but still there is much that is fair.", author: "J.R.R. Tolkien", category: "Literature" },
  { id: 312, text: "Don't tell me the moon is shining; show me the glint of light on broken glass.", author: "Anton Chekhov", category: "Literature" },
  { id: 313, text: "Knowledge is of no value unless you put it into practice.", author: "Anton Chekhov", category: "Education" },
  { id: 314, text: "Maybe that's what life is... a wink of the eye and winking stars.", author: "Jack Kerouac", category: "Literature" },
  { id: 315, text: "The only people for me are the mad ones, the ones who are mad to live, mad to talk, mad to be saved.", author: "Jack Kerouac", category: "Literature" },
  { id: 316, text: "There was nowhere to go but everywhere, so just keep on rolling under the stars.", author: "Jack Kerouac", category: "Literature" },
  { id: 317, text: "Great things never came from comfort zones.", author: "Anonymous", category: "Motivation" },
  { id: 318, text: "The most dangerous phrase in the language is: 'We've always done it this way.'", author: "Grace Hopper", category: "Innovation" },
  { id: 319, text: "A ship in port is safe, but that's not what ships are built for.", author: "Grace Hopper", category: "Courage" },
  { id: 320, text: "The greatest enemy of knowledge is not ignorance, it is the illusion of knowledge.", author: "Stephen Hawking", category: "Science" },
  { id: 321, text: "Intelligence is the ability to adapt to change.", author: "Stephen Hawking", category: "Science" },
  { id: 322, text: "However difficult life may seem, there is always something you can do and succeed at.", author: "Stephen Hawking", category: "Motivation" },
  { id: 323, text: "Look up at the stars and not down at your feet. Try to make sense of what you see, and wonder about what makes the universe exist.", author: "Stephen Hawking", category: "Science" },
  { id: 324, text: "We are just an advanced breed of monkeys on a minor planet of a very average star. But we can understand the universe. That makes us something very special.", author: "Stephen Hawking", category: "Science" },
  { id: 325, text: "Time is what keeps everything from happening at once.", author: "Ray Cummings", category: "Science" },
  { id: 326, text: "Eureka!", author: "Archimedes", category: "Science" },
  { id: 327, text: "Give me a lever long enough and a fulcrum on which to place it, and I shall move the world.", author: "Archimedes", category: "Science" },
  { id: 328, text: "The scientist is not a person who gives the right answers, but one who asks the right questions.", author: "Claude Lévi-Strauss", category: "Science" },
  { id: 329, text: "The important thing in science is not so much to obtain new facts as to discover new ways of thinking about them.", author: "William Lawrence Bragg", category: "Science" },
  { id: 330, text: "Equipped with his five senses, man explores the universe around him and calls the adventure Science.", author: "Edwin Hubble", category: "Science" },
  { id: 331, text: "I believe that a scientist looking at nonscientific problems is just as dumb as the next guy.", author: "Richard Feynman", category: "Science" },
  { id: 332, text: "The first principle is that you must not fool yourself — and you are the easiest person to fool.", author: "Richard Feynman", category: "Science" },
  { id: 333, text: "What I cannot create, I do not understand.", author: "Richard Feynman", category: "Science" },
  { id: 334, text: "Physics is like sex: sure, it may give some practical results, but that's not why we do it.", author: "Richard Feynman", category: "Science" },
  { id: 335, text: "We are all connected; to each other, biologically. To the earth, chemically. To the rest of the universe, atomically.", author: "Neil deGrasse Tyson", category: "Science" },
  { id: 336, text: "The good thing about science is that it's true whether or not you believe in it.", author: "Neil deGrasse Tyson", category: "Science" },
  { id: 337, text: "Curiosity is the engine of achievement.", author: "Ken Robinson", category: "Education" },
  { id: 338, text: "Creativity is as important as literacy.", author: "Ken Robinson", category: "Creativity" },
  { id: 339, text: "If you're not prepared to be wrong, you'll never come up with anything original.", author: "Ken Robinson", category: "Creativity" },
  { id: 340, text: "The role of a creative leader is not to have all the ideas; it's to create a culture where everyone can have ideas.", author: "Ken Robinson", category: "Creativity" },
  { id: 341, text: "Imagination is the source of every form of human achievement.", author: "Ken Robinson", category: "Creativity" },
  { id: 342, text: "You cannot pour from an empty cup. Take care of yourself first.", author: "Anonymous", category: "Self-care" },
  { id: 343, text: "Almost everything will work again if you unplug it for a few minutes, including you.", author: "Anne Lamott", category: "Self-care" },
  { id: 344, text: "Rest when you're weary. Refresh and renew yourself, your body, your mind, your spirit.", author: "Anonymous", category: "Self-care" },
  { id: 345, text: "Your body hears everything your mind says.", author: "Naomi Judd", category: "Health" },
  { id: 346, text: "Take care of your body. It's the only place you have to live.", author: "Jim Rohn", category: "Health" },
  { id: 347, text: "The greatest wealth is health.", author: "Virgil", category: "Health" },
  { id: 348, text: "He who has health has hope, and he who has hope has everything.", author: "Arabian Proverb", category: "Health" },
  { id: 349, text: "A healthy outside starts from the inside.", author: "Robert Urich", category: "Health" },
  { id: 350, text: "The secret of change is to focus all of your energy not on fighting the old, but on building the new.", author: "Socrates", category: "Change" },
  { id: 351, text: "Change is the law of life. And those who look only to the past or present are certain to miss the future.", author: "John F. Kennedy", category: "Change" },
  { id: 352, text: "Progress is impossible without change, and those who cannot change their minds cannot change anything.", author: "George Bernard Shaw", category: "Change" },
  { id: 353, text: "The measure of intelligence is the ability to change.", author: "Albert Einstein", category: "Change" },
  { id: 354, text: "To improve is to change; to be perfect is to change often.", author: "Winston Churchill", category: "Change" },
  { id: 355, text: "It is not the strongest of the species that survive, nor the most intelligent, but the one most responsive to change.", author: "Charles Darwin", category: "Change" },
  { id: 356, text: "Life is about not knowing, having to change, taking the moment and making the best of it, without knowing what's going to happen next.", author: "Gilda Radner", category: "Life" },
  { id: 357, text: "The measure of a man is what he does with power.", author: "Plato", category: "Philosophy" },
  { id: 358, text: "We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.", author: "Plato", category: "Philosophy" },
  { id: 359, text: "Courage is knowing what not to fear.", author: "Plato", category: "Courage" },
  { id: 360, text: "The greatest wealth is to live content with little.", author: "Plato", category: "Wisdom" },
  { id: 361, text: "Happiness is the highest good.", author: "Aristotle", category: "Philosophy" },
  { id: 362, text: "Patience is bitter, but its fruit is sweet.", author: "Aristotle", category: "Wisdom" },
  { id: 363, text: "The whole is greater than the sum of its parts.", author: "Aristotle", category: "Philosophy" },
  { id: 364, text: "Pleasure in the job puts perfection in the work.", author: "Aristotle", category: "Motivation" },
  { id: 365, text: "It is the mark of an educated mind to be able to entertain a thought without accepting it.", author: "Aristotle", category: "Education" },
];
